package com.multiplay.admin;

import android.app.*;
import android.os.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.regex.*;

public class MainActivity extends Activity {
  final String API="https://multiplay-site.onrender.com";
  LinearLayout root,body; android.content.SharedPreferences prefs;
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(size);t.setPadding(dp(8),dp(7),dp(8),dp(7));if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
  Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackgroundColor(Color.rgb(22,140,255));return b;}
  EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(130,145,165));e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(10,18,32));g.setStroke(dp(1),Color.rgb(32,49,73));g.setCornerRadius(dp(10));e.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(5),0,dp(5));e.setLayoutParams(p);return e;}
  public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("admin",0);login();}
  void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(16));root.setBackgroundColor(Color.rgb(3,7,18));setContentView(root);}
  void login(){base();Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,dp(35)));TextView logo=text("MULTIPLAY",32,true);logo.setTextColor(Color.rgb(24,221,255));logo.setGravity(Gravity.CENTER);root.addView(logo,new LinearLayout.LayoutParams(-1,dp(65)));TextView sub=text("PAINEL ADMINISTRATIVO",15,true);sub.setGravity(Gravity.CENTER);root.addView(sub,new LinearLayout.LayoutParams(-1,dp(35)));root.addView(text("Acesse o painel para administrar clientes e dispositivos.",14,false));EditText u=input("Usuário administrador");EditText p=input("Senha");p.setInputType(0x81);root.addView(u);root.addView(p);Button b=button("ENTRAR NO PAINEL");root.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));TextView msg=text("",13,false);root.addView(msg);b.setOnClickListener(v->doLogin(u.getText().toString().trim(),p.getText().toString(),msg));}
  void doLogin(String u,String pw,TextView msg){if(u.isEmpty()||pw.isEmpty()){msg.setText("Informe usuário e senha.");return;}msg.setText("Entrando...");new Thread(()->{try{String json=post("/api/login",String.format("{\"username\":\"%s\",\"password\":\"%s\"}",esc(u),esc(pw)),null);boolean ok=json.contains("\"success\":true");runOnUiThread(()->{if(ok){home();}else msg.setText("Usuário ou senha inválidos.");});}catch(Exception e){runOnUiThread(()->msg.setText("Não foi possível conectar ao servidor."));}}).start();}
  String esc(String s){return s.replace("\\","\\\\").replace("\"","\\\"");}
  String cookies="";
  String request(String method,String path,String body)throws Exception{URL url=new URL(API+path);HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/json");if(!cookies.isEmpty())c.setRequestProperty("Cookie",cookies);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}String set=c.getHeaderField("Set-Cookie");if(set!=null){String v=set.split(";",2)[0];cookies=v;}InputStream in=(c.getResponseCode()>=400?c.getErrorStream():c.getInputStream());if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);return s.toString();}
  String post(String p,String b,String c)throws Exception{return request("POST",p,b);}
  void home(){base();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView logo=text("MULTIPLAY PAINEL",22,true);logo.setTextColor(Color.rgb(24,221,255));top.addView(logo,new LinearLayout.LayoutParams(0,dp(55),1));Button out=button("Sair");top.addView(out,new LinearLayout.LayoutParams(dp(65),dp(45)));out.setOnClickListener(v->{cookies="";login();});root.addView(top);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);String[] ns={"VISÃO GERAL","DISPOSITIVOS","CLIENTES"};for(String n:ns){Button x=button(n);nav.addView(x,new LinearLayout.LayoutParams(0,dp(48),1));if(n.startsWith("DIS"))x.setOnClickListener(v->devices());else if(n.startsWith("CLI"))x.setOnClickListener(v->clients());else x.setOnClickListener(v->overview());}root.addView(nav);overview();}
  void clear(){body.removeAllViews();}
  void overview(){clear();body.addView(text("Painel Multiplay",26,true));body.addView(text("Administre ativações e acesso aos conteúdos autorizados.",14,false));LinearLayout g=new LinearLayout(this);g.setOrientation(LinearLayout.VERTICAL);String[] a={"📱 Dispositivos","👤 Clientes","🔗 Playlists autorizadas","📅 Validades e status"};for(String s:a){TextView c=text(s,17,true);c.setGravity(Gravity.CENTER_VERTICAL);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(10,18,32));bg.setStroke(dp(1),Color.rgb(32,49,73));bg.setCornerRadius(dp(12));c.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,dp(6),0,dp(6));g.addView(c,p);}body.addView(g);}
  void devices(){clear();body.addView(text("📱 Dispositivos",25,true));body.addView(text("Cadastre o Device ID/Key e vincule somente playlists autorizadas.",12,false));EditText id=input("Device ID");EditText key=input("Device Key");EditText user=input("Cliente / usuário");EditText name=input("Nome da playlist");EditText url=input("URL M3U autorizada");EditText epg=input("URL EPG (opcional)");body.addView(id);body.addView(key);body.addView(user);body.addView(name);body.addView(url);body.addView(epg);CheckBox active=new CheckBox(this);active.setText("Dispositivo ativo");active.setTextColor(Color.WHITE);active.setChecked(true);body.addView(active);Button save=button("SALVAR / ATUALIZAR DISPOSITIVO");body.addView(save,new LinearLayout.LayoutParams(-1,dp(50)));TextView msg=text("",12,false);body.addView(msg);save.setOnClickListener(v->saveDevice(id,key,user,name,url,epg,active,msg));Button list=button("ATUALIZAR LISTA");body.addView(list,new LinearLayout.LayoutParams(-1,dp(45)));list.setOnClickListener(v->loadDevices());loadDevices();}
  void saveDevice(EditText id,EditText key,EditText user,EditText name,EditText url,EditText epg,CheckBox active,TextView msg){String bodyJson="{\"device_id\":\""+esc(id.getText().toString().trim())+"\",\"device_key\":\""+esc(key.getText().toString().trim())+"\",\"customer_username\":\""+esc(user.getText().toString().trim())+"\",\"playlist_name\":\""+esc(name.getText().toString().trim())+"\",\"playlist_url\":\""+esc(url.getText().toString().trim())+"\",\"epg_url\":\""+esc(epg.getText().toString().trim())+"\",\"active\":"+active.isChecked()+"}";msg.setText("Salvando...");new Thread(()->{try{String r=post("/api/admin/devices",bodyJson,null);runOnUiThread(()->{msg.setText(r.contains("\"success\":true")?"Dispositivo atualizado.":"Erro ao salvar.");loadDevices();});}catch(Exception e){runOnUiThread(()->msg.setText("Falha de conexão."));}}).start();}
  void loadDevices(){new Thread(()->{try{String r=request("GET","/api/admin/devices",null);runOnUiThread(()->showDeviceList(r));}catch(Exception e){runOnUiThread(()->{});}}).start();}
  void showDeviceList(String json){TextView title=text("Dispositivos cadastrados",18,true);body.addView(title);if(json.contains("\"success\":true")){Matcher m=Pattern.compile("\\\"device_id\\\":\\\"(.*?)\\\"").matcher(json);int n=0;while(m.find()&&n<50){TextView d=text("• "+m.group(1),14,true);body.addView(d);n++;}}else body.addView(text("Sessão expirada ou sem acesso.",13,false));}
  void clients(){clear();body.addView(text("👤 Clientes",25,true));body.addView(text("Clientes criados no painel web aparecem aqui.",12,false));Button refresh=button("CARREGAR CLIENTES");body.addView(refresh,new LinearLayout.LayoutParams(-1,dp(48)));TextView list=text("Carregando...",13,false);ScrollView sv=new ScrollView(this);sv.addView(list);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));refresh.setOnClickListener(v->loadClients(list));loadClients(list);}
  void loadClients(TextView out){new Thread(()->{try{String r=request("GET","/api/admin/users",null);runOnUiThread(()->{Matcher m=Pattern.compile("\\\"username\\\":\\\"(.*?)\\\"").matcher(r);StringBuilder s=new StringBuilder();int n=0;while(m.find()&&n<100){s.append("• ").append(m.group(1)).append("\n");n++;}out.setText(n==0?"Nenhum cliente encontrado.":s.toString());});}catch(Exception e){runOnUiThread(()->out.setText("Não foi possível carregar clientes."));}}).start();}
}
