plugins { id 'com.android.application' }
android {
    namespace 'com.multiplay.educacao'
    compileSdk 35
    defaultConfig {
        applicationId 'com.multiplay.educacao'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.2.2'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.13.0'
}