name: Gerar APK MultiPlay

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  android:
    name: Construir aplicativo Android
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependências
        run: npm install

      - name: Criar projeto Android
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Gerar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: MultiPlay-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
